apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: apicurio
  namespace: default
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        appstudio.openshift.io/application: appstudio
        appstudio.openshift.io/component: apicurio
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: apicurio-
      labels:
        appstudio.openshift.io/application: appstudio
        appstudio.openshift.io/component: apicurio
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: default
    spec:
      params:
      - name: git-url
        value: https://github.com/scoheb/apicurio-registry.git
      - name: output-image
        value: quay.io/redhat-appstudio/user-workload:default-apicurio-$(tt.params.git-revision)
      pipelineRef:
        bundle: quay.io/redhat-appstudio/hacbs-templates-bundle:latest
        name: java-builder
      workspaces:
      - name: workspace
        volumeClaimTemplate:
          metadata:
            creationTimestamp: null
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
          status: {}
    status: {}
status: {}
